-- AlterTable
ALTER TABLE `ShopItem` ADD COLUMN `positionX` DOUBLE NOT NULL DEFAULT 50,
    ADD COLUMN `positionY` DOUBLE NOT NULL DEFAULT 50,
    ADD COLUMN `scale` DOUBLE NOT NULL DEFAULT 1.0,
    ADD COLUMN `zIndex` INTEGER NOT NULL DEFAULT 1;
